version: '{build}'
image: Visual Studio 2017

environment:
  RepoName: bob-scoop
  NuGet_PackageId: Unic.Bob.Scoop
  Nuspec_File: .\%NuGet_PackageId%.nuspec
  NuGetToken:
    secure: jhODVb/iVko3b4Y9p1tOMP9LeDy6OQEYePDIDT6lfAOgNnJixjJpJBAJj/gtkDLc
  Artefact_Output_Dir: .\output
  GithubEmail: team-unic@unic.com
  GithubUsername: team-unic
  GithubAccessTokenTeamUnic:
    secure: BCEthL/NRFeg5eKK9CgmwbySILxWjMUjpvExHC0oGl1jjAT4kMBAohzh9m/xsVDh

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver
  - ps: .\restore.ps1

  # Setup GIT
  - git config --global user.email %GithubEmail%
  - git config --global user.name %GithubUsername%
  - git config --global push.default simple
  - git config --global core.autocrlf true
  - git config --global core.safecrlf false
  - git config --global credential.helper store
  
assembly_info:
  patch: false

build_script:
  - cmd: nuget pack %Nuspec_File% -version "%GitVersion_NuGetVersionV2%" -OutputDirectory %Artefact_Output_Dir%

after_build:
  - cmd: appveyor PushArtifact %Artefact_Output_Dir%\%NuGet_PackageId%.%GitVersion_NuGetVersionV2%.nupkg

test_script:
  - ps: .\runTests.ps1

deploy_script:
  - ps: |
      $ErrorActionPreference = 'Stop';
      if($env:appveyor_repo_tag -eq 'true') {
        Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GithubAccessTokenTeamUnic):x-oauth-basic@github.com`n";
        .\pushDocs.ps1 $env:APPVEYOR_BUILD_FOLDER docs-generated\_book https://github.com/unic/$($env:RepoName).git
      }
deploy:
  - provider: Environment
    name: NuGet.org
    on:
      branch: master
  - provider: Environment
    name: NuGet.org
    on:
      appveyor_repo_tag: true
